### PR TITLE
CleanUp: Removed unused variables added responsiveness

### PR DESCRIPTION
**Pull request by JasonRHemann**
Cleaned up most errors.  Added alt's to images.  Fixed Responsiveness on a header, searchbar, and satellite button

### CODE REVIEW

**Review by ousbayaa — DISMISSED** [review]
Clear and concise code for added responsiveness

**Review by matthew-kearney — DISMISSED** [review]
These changes look good.

**Review by matthew-kearney — APPROVED** [review]
approving again

**Review by ShotaKiko — APPROVED** [review]
Changes look good, a lot of unused code. Nice work! For additional cleaning you could removing the clustering dependency as well

**Pull request merged**
